language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build
  # - npm test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  target_branch: gh-pages
